//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowApp.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUsHeader {
            get {
                return ResourceManager.GetString("AboutUsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string AdminHeader {
            get {
                return ResourceManager.GetString("AdminHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactHeader {
            get {
                return ResourceManager.GetString("ContactHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string ContractHeader {
            get {
                return ResourceManager.GetString("ContractHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English for children and adults — group and individual lessons.
        ///We help you speak confidently and improve your results in studies or at work..
        /// </summary>
        public static string Hero_Lead_1 {
            get {
                return ResourceManager.GetString("Hero_Lead_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOutHeader {
            get {
                return ResourceManager.GetString("LogOutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string PortfolioHeader {
            get {
                return ResourceManager.GetString("PortfolioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Sign-Up.
        /// </summary>
        public static string QuickSignUpHome {
            get {
                return ResourceManager.GetString("QuickSignUpHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string ReviewHeader {
            get {
                return ResourceManager.GetString("ReviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string ServiceHeader {
            get {
                return ResourceManager.GetString("ServiceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string TextAboutUs_1 {
            get {
                return ResourceManager.GetString("TextAboutUs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Club Teacher.
        /// </summary>
        public static string TextAboutUs_10 {
            get {
                return ResourceManager.GetString("TextAboutUs_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liubov Romanivna Vinnytska.
        /// </summary>
        public static string TextAboutUs_11 {
            get {
                return ResourceManager.GetString("TextAboutUs_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A teacher is a professional who will help you learn the language..
        /// </summary>
        public static string TextAboutUs_12 {
            get {
                return ResourceManager.GetString("TextAboutUs_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Goal.
        /// </summary>
        public static string TextAboutUs_13 {
            get {
                return ResourceManager.GetString("TextAboutUs_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To give you confidence and practical skills so that English becomes a tool, not a “scary subject.”.
        /// </summary>
        public static string TextAboutUs_14 {
            get {
                return ResourceManager.GetString("TextAboutUs_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string TextAboutUs_15 {
            get {
                return ResourceManager.GetString("TextAboutUs_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small groups and individual lessons. Speaking practice in every class, modern topics, and lively dialogues..
        /// </summary>
        public static string TextAboutUs_16 {
            get {
                return ResourceManager.GetString("TextAboutUs_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string TextAboutUs_17 {
            get {
                return ResourceManager.GetString("TextAboutUs_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will see real progress: a stronger vocabulary, grammar without “cramming,” and better listening comprehension..
        /// </summary>
        public static string TextAboutUs_18 {
            get {
                return ResourceManager.GetString("TextAboutUs_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Is English Club For?.
        /// </summary>
        public static string TextAboutUs_19 {
            get {
                return ResourceManager.GetString("TextAboutUs_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string TextAboutUs_2 {
            get {
                return ResourceManager.GetString("TextAboutUs_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For students, adults, and teenagers who want to learn English clearly and systematically. We select groups based on your level and goals: work, studies, travel, or exams..
        /// </summary>
        public static string TextAboutUs_20 {
            get {
                return ResourceManager.GetString("TextAboutUs_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginners (A1–A2): fundamentals, pronunciation, simple dialogues.
        /// </summary>
        public static string TextAboutUs_21 {
            get {
                return ResourceManager.GetString("TextAboutUs_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate level (B1–B2): speaking confidence + grammar.
        /// </summary>
        public static string TextAboutUs_22 {
            get {
                return ResourceManager.GetString("TextAboutUs_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced (C1): fluency, professional and academic English.
        /// </summary>
        public static string TextAboutUs_23 {
            get {
                return ResourceManager.GetString("TextAboutUs_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Prices and Formats.
        /// </summary>
        public static string TextAboutUs_24 {
            get {
                return ResourceManager.GetString("TextAboutUs_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Get Started.
        /// </summary>
        public static string TextAboutUs_25 {
            get {
                return ResourceManager.GetString("TextAboutUs_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit an application (1 minute).
        /// </summary>
        public static string TextAboutUs_26 {
            get {
                return ResourceManager.GetString("TextAboutUs_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a short level assessment.
        /// </summary>
        public static string TextAboutUs_27 {
            get {
                return ResourceManager.GetString("TextAboutUs_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a group/format recommendation.
        /// </summary>
        public static string TextAboutUs_28 {
            get {
                return ResourceManager.GetString("TextAboutUs_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start learning.
        /// </summary>
        public static string TextAboutUs_29 {
            get {
                return ResourceManager.GetString("TextAboutUs_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Club is an English school where things are explained simply and real results are achieved..
        /// </summary>
        public static string TextAboutUs_3 {
            get {
                return ResourceManager.GetString("TextAboutUs_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ — quick answers to the most important questions.
        /// </summary>
        public static string TextAboutUs_30 {
            get {
                return ResourceManager.GetString("TextAboutUs_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I learn grammar without “cramming”?.
        /// </summary>
        public static string TextAboutUs_31 {
            get {
                return ResourceManager.GetString("TextAboutUs_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. We explain grammar using simple examples and immediately reinforce it through speaking and practical exercises..
        /// </summary>
        public static string TextAboutUs_32 {
            get {
                return ResourceManager.GetString("TextAboutUs_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many lessons are needed to see progress?.
        /// </summary>
        public static string TextAboutUs_33 {
            get {
                return ResourceManager.GetString("TextAboutUs_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first changes are noticeable after 3–4 weeks of regular classes, and a clear improvement can be seen within 2–3 months..
        /// </summary>
        public static string TextAboutUs_34 {
            get {
                return ResourceManager.GetString("TextAboutUs_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online or offline — which is better?.
        /// </summary>
        public static string TextAboutUs_35 {
            get {
                return ResourceManager.GetString("TextAboutUs_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both formats work well. Online is convenient from any city, while offline is perfect if you enjoy a “live” classroom. We’ll choose what fits your pace best..
        /// </summary>
        public static string TextAboutUs_36 {
            get {
                return ResourceManager.GetString("TextAboutUs_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started?.
        /// </summary>
        public static string TextAboutUs_37 {
            get {
                return ResourceManager.GetString("TextAboutUs_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up — and we’ll help you choose the right level and group..
        /// </summary>
        public static string TextAboutUs_38 {
            get {
                return ResourceManager.GetString("TextAboutUs_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string TextAboutUs_39 {
            get {
                return ResourceManager.GetString("TextAboutUs_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help you speak confidently, understand others, and use English in real life — or studying, work, travel, and everyday communication..
        /// </summary>
        public static string TextAboutUs_4 {
            get {
                return ResourceManager.GetString("TextAboutUs_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll in a Class.
        /// </summary>
        public static string TextAboutUs_5 {
            get {
                return ResourceManager.GetString("TextAboutUs_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TextAboutUs_6 {
            get {
                return ResourceManager.GetString("TextAboutUs_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels A1–C1.
        /// </summary>
        public static string TextAboutUs_7 {
            get {
                return ResourceManager.GetString("TextAboutUs_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual and Group Classes.
        /// </summary>
        public static string TextAboutUs_8 {
            get {
                return ResourceManager.GetString("TextAboutUs_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online or Offline.
        /// </summary>
        public static string TextAboutUs_9 {
            get {
                return ResourceManager.GetString("TextAboutUs_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our English Club uses modern teaching methods. We help you learn to speak English easily and with confidence..
        /// </summary>
        public static string TextFooter_1 {
            get {
                return ResourceManager.GetString("TextFooter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string TextFooter_10 {
            get {
                return ResourceManager.GetString("TextFooter_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string TextFooter_2 {
            get {
                return ResourceManager.GetString("TextFooter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string TextFooter_3 {
            get {
                return ResourceManager.GetString("TextFooter_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string TextFooter_4 {
            get {
                return ResourceManager.GetString("TextFooter_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Services.
        /// </summary>
        public static string TextFooter_5 {
            get {
                return ResourceManager.GetString("TextFooter_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string TextFooter_6 {
            get {
                return ResourceManager.GetString("TextFooter_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string TextFooter_7 {
            get {
                return ResourceManager.GetString("TextFooter_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Story.
        /// </summary>
        public static string TextFooter_8 {
            get {
                return ResourceManager.GetString("TextFooter_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stryi, Okhrymovycha St., 8/25.
        /// </summary>
        public static string TextFooter_9 {
            get {
                return ResourceManager.GetString("TextFooter_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free trial lesson — we’ll assess your English level and find the learning format that works best for you..
        /// </summary>
        public static string TextHome_1 {
            get {
                return ResourceManager.GetString("TextHome_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (special course).
        /// </summary>
        public static string TextHome_10 {
            get {
                return ResourceManager.GetString("TextHome_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English for Travel.
        /// </summary>
        public static string TextHome_11 {
            get {
                return ResourceManager.GetString("TextHome_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (practical course).
        /// </summary>
        public static string TextHome_12 {
            get {
                return ResourceManager.GetString("TextHome_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEEP IMPROVING.
        /// </summary>
        public static string TextHome_13 {
            get {
                return ResourceManager.GetString("TextHome_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking Club.
        /// </summary>
        public static string TextHome_14 {
            get {
                return ResourceManager.GetString("TextHome_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (speaking practice).
        /// </summary>
        public static string TextHome_15 {
            get {
                return ResourceManager.GetString("TextHome_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Days.
        /// </summary>
        public static string TextHome_16 {
            get {
                return ResourceManager.GetString("TextHome_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (english through movies).
        /// </summary>
        public static string TextHome_17 {
            get {
                return ResourceManager.GetString("TextHome_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookworm Club.
        /// </summary>
        public static string TextHome_18 {
            get {
                return ResourceManager.GetString("TextHome_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (book lovers’ club).
        /// </summary>
        public static string TextHome_19 {
            get {
                return ResourceManager.GetString("TextHome_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a callback — our manager will get in touch with you to discuss your goals and recommend the best learning option for you..
        /// </summary>
        public static string TextHome_2 {
            get {
                return ResourceManager.GetString("TextHome_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karaoke Days.
        /// </summary>
        public static string TextHome_20 {
            get {
                return ResourceManager.GetString("TextHome_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (english with songs).
        /// </summary>
        public static string TextHome_21 {
            get {
                return ResourceManager.GetString("TextHome_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOVER THE WORLD WITH US.
        /// </summary>
        public static string TextHome_22 {
            get {
                return ResourceManager.GetString("TextHome_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for children and adults.
        /// </summary>
        public static string TextHome_23 {
            get {
                return ResourceManager.GetString("TextHome_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group lessons.
        /// </summary>
        public static string TextHome_24 {
            get {
                return ResourceManager.GetString("TextHome_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to individual lessons.
        /// </summary>
        public static string TextHome_25 {
            get {
                return ResourceManager.GetString("TextHome_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to corporate training.
        /// </summary>
        public static string TextHome_26 {
            get {
                return ResourceManager.GetString("TextHome_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online lessons.
        /// </summary>
        public static string TextHome_27 {
            get {
                return ResourceManager.GetString("TextHome_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to individual approach.
        /// </summary>
        public static string TextHome_28 {
            get {
                return ResourceManager.GetString("TextHome_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string TextHome_29 {
            get {
                return ResourceManager.GetString("TextHome_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon–Fri 9:00–21:00 • Sat 9:00–15:00 • Sun closed.
        /// </summary>
        public static string TextHome_3 {
            get {
                return ResourceManager.GetString("TextHome_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday–Friday.
        /// </summary>
        public static string TextHome_30 {
            get {
                return ResourceManager.GetString("TextHome_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string TextHome_31 {
            get {
                return ResourceManager.GetString("TextHome_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string TextHome_32 {
            get {
                return ResourceManager.GetString("TextHome_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day off.
        /// </summary>
        public static string TextHome_33 {
            get {
                return ResourceManager.GetString("TextHome_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TextHome_34 {
            get {
                return ResourceManager.GetString("TextHome_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TextHome_35 {
            get {
                return ResourceManager.GetString("TextHome_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free lesson.
        /// </summary>
        public static string TextHome_36 {
            get {
                return ResourceManager.GetString("TextHome_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        public static string TextHome_37 {
            get {
                return ResourceManager.GetString("TextHome_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN.
        /// </summary>
        public static string TextHome_4 {
            get {
                return ResourceManager.GetString("TextHome_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English for Real Life.
        /// </summary>
        public static string TextHome_5 {
            get {
                return ResourceManager.GetString("TextHome_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (conversational english).
        /// </summary>
        public static string TextHome_6 {
            get {
                return ResourceManager.GetString("TextHome_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English for Studying.
        /// </summary>
        public static string TextHome_7 {
            get {
                return ResourceManager.GetString("TextHome_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparation for ZNO / Entrance Exams.
        /// </summary>
        public static string TextHome_8 {
            get {
                return ResourceManager.GetString("TextHome_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business English.
        /// </summary>
        public static string TextHome_9 {
            get {
                return ResourceManager.GetString("TextHome_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TextOurContacts_1 {
            get {
                return ResourceManager.GetString("TextOurContacts_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string TextOurContacts_10 {
            get {
                return ResourceManager.GetString("TextOurContacts_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a question or want to enroll your child in classes? Message us — we’ll quickly help you choose the right format and level..
        /// </summary>
        public static string TextOurContacts_11 {
            get {
                return ResourceManager.GetString("TextOurContacts_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TextOurContacts_12 {
            get {
                return ResourceManager.GetString("TextOurContacts_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TextOurContacts_13 {
            get {
                return ResourceManager.GetString("TextOurContacts_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on the map →.
        /// </summary>
        public static string TextOurContacts_14 {
            get {
                return ResourceManager.GetString("TextOurContacts_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll match you with a group based on age and level — just message us “I want to learn.”.
        /// </summary>
        public static string TextOurContacts_15 {
            get {
                return ResourceManager.GetString("TextOurContacts_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a Request.
        /// </summary>
        public static string TextOurContacts_16 {
            get {
                return ResourceManager.GetString("TextOurContacts_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the form — we’ll get in touch with you as soon as possible..
        /// </summary>
        public static string TextOurContacts_17 {
            get {
                return ResourceManager.GetString("TextOurContacts_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextOurContacts_18 {
            get {
                return ResourceManager.GetString("TextOurContacts_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TextOurContacts_19 {
            get {
                return ResourceManager.GetString("TextOurContacts_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string TextOurContacts_2 {
            get {
                return ResourceManager.GetString("TextOurContacts_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string TextOurContacts_20 {
            get {
                return ResourceManager.GetString("TextOurContacts_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending….
        /// </summary>
        public static string TextOurContacts_21 {
            get {
                return ResourceManager.GetString("TextOurContacts_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Application.
        /// </summary>
        public static string TextOurContacts_22 {
            get {
                return ResourceManager.GetString("TextOurContacts_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string TextOurContacts_23 {
            get {
                return ResourceManager.GetString("TextOurContacts_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stryi, Okhrymovycha St., 8/25.
        /// </summary>
        public static string TextOurContacts_24 {
            get {
                return ResourceManager.GetString("TextOurContacts_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day off.
        /// </summary>
        public static string TextOurContacts_25 {
            get {
                return ResourceManager.GetString("TextOurContacts_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent from the Contacts page..
        /// </summary>
        public static string TextOurContacts_26 {
            get {
                return ResourceManager.GetString("TextOurContacts_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending. Please try again..
        /// </summary>
        public static string TextOurContacts_27 {
            get {
                return ResourceManager.GetString("TextOurContacts_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! We’ve received your message and will contact you shortly..
        /// </summary>
        public static string TextOurContacts_28 {
            get {
                return ResourceManager.GetString("TextOurContacts_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Contacts.
        /// </summary>
        public static string TextOurContacts_3 {
            get {
                return ResourceManager.GetString("TextOurContacts_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write or call us — we’ll recommend the right learning format, assess your level, and help you choose a group..
        /// </summary>
        public static string TextOurContacts_4 {
            get {
                return ResourceManager.GetString("TextOurContacts_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string TextOurContacts_5 {
            get {
                return ResourceManager.GetString("TextOurContacts_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We respond quickly.
        /// </summary>
        public static string TextOurContacts_6 {
            get {
                return ResourceManager.GetString("TextOurContacts_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon–Fri.
        /// </summary>
        public static string TextOurContacts_7 {
            get {
                return ResourceManager.GetString("TextOurContacts_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string TextOurContacts_8 {
            get {
                return ResourceManager.GetString("TextOurContacts_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string TextOurContacts_9 {
            get {
                return ResourceManager.GetString("TextOurContacts_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TextOurReviews_1 {
            get {
                return ResourceManager.GetString("TextOurReviews_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfort.
        /// </summary>
        public static string TextOurReviews_10 {
            get {
                return ResourceManager.GetString("TextOurReviews_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Review.
        /// </summary>
        public static string TextOurReviews_11 {
            get {
                return ResourceManager.GetString("TextOurReviews_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Reviews.
        /// </summary>
        public static string TextOurReviews_12 {
            get {
                return ResourceManager.GetString("TextOurReviews_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can browse and search by keywords.
        /// </summary>
        public static string TextOurReviews_13 {
            get {
                return ResourceManager.GetString("TextOurReviews_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (name, text, tag)....
        /// </summary>
        public static string TextOurReviews_14 {
            get {
                return ResourceManager.GetString("TextOurReviews_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string TextOurReviews_15 {
            get {
                return ResourceManager.GetString("TextOurReviews_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string TextOurReviews_16 {
            get {
                return ResourceManager.GetString("TextOurReviews_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try changing your search query..
        /// </summary>
        public static string TextOurReviews_17 {
            get {
                return ResourceManager.GetString("TextOurReviews_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown.
        /// </summary>
        public static string TextOurReviews_18 {
            get {
                return ResourceManager.GetString("TextOurReviews_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string TextOurReviews_19 {
            get {
                return ResourceManager.GetString("TextOurReviews_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string TextOurReviews_2 {
            get {
                return ResourceManager.GetString("TextOurReviews_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Reviews.
        /// </summary>
        public static string TextOurReviews_3 {
            get {
                return ResourceManager.GetString("TextOurReviews_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s important to us that learning is comfortable and delivers real results. Here’s what our students say..
        /// </summary>
        public static string TextOurReviews_4 {
            get {
                return ResourceManager.GetString("TextOurReviews_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string TextOurReviews_5 {
            get {
                return ResourceManager.GetString("TextOurReviews_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string TextOurReviews_6 {
            get {
                return ResourceManager.GetString("TextOurReviews_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We explain things simply.
        /// </summary>
        public static string TextOurReviews_7 {
            get {
                return ResourceManager.GetString("TextOurReviews_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking Practice.
        /// </summary>
        public static string TextOurReviews_8 {
            get {
                return ResourceManager.GetString("TextOurReviews_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string TextOurReviews_9 {
            get {
                return ResourceManager.GetString("TextOurReviews_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TextPortfolio_1 {
            get {
                return ResourceManager.GetString("TextPortfolio_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string TextPortfolio_2 {
            get {
                return ResourceManager.GetString("TextPortfolio_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Portfolio.
        /// </summary>
        public static string TextPortfolio_3 {
            get {
                return ResourceManager.GetString("TextPortfolio_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liubov Romanivna.
        /// </summary>
        public static string TextPortfolio_4 {
            get {
                return ResourceManager.GetString("TextPortfolio_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TextServices_1 {
            get {
                return ResourceManager.GetString("TextServices_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sure what to choose?.
        /// </summary>
        public static string TextServices_10 {
            get {
                return ResourceManager.GetString("TextServices_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message us — we’ll help you choose the best option based on your needs and desired results..
        /// </summary>
        public static string TextServices_11 {
            get {
                return ResourceManager.GetString("TextServices_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Consultation.
        /// </summary>
        public static string TextServices_12 {
            get {
                return ResourceManager.GetString("TextServices_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback Request.
        /// </summary>
        public static string TextServices_13 {
            get {
                return ResourceManager.GetString("TextServices_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string TextServices_2 {
            get {
                return ResourceManager.GetString("TextServices_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string TextServices_3 {
            get {
                return ResourceManager.GetString("TextServices_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning English.
        /// </summary>
        public static string TextServices_4 {
            get {
                return ResourceManager.GetString("TextServices_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn English through practice, communication, and engaging tasks. We’ll choose a learning format that matches your level and goals..
        /// </summary>
        public static string TextServices_5 {
            get {
                return ResourceManager.GetString("TextServices_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of Classes.
        /// </summary>
        public static string TextServices_6 {
            get {
                return ResourceManager.GetString("TextServices_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of class that suits you — we’ll clarify the details and find a convenient time..
        /// </summary>
        public static string TextServices_7 {
            get {
                return ResourceManager.GetString("TextServices_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH.
        /// </summary>
        public static string TextServices_8 {
            get {
                return ResourceManager.GetString("TextServices_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        public static string TextServices_9 {
            get {
                return ResourceManager.GetString("TextServices_9", resourceCulture);
            }
        }
    }
}
